
language: node_js
node_js:
- stable
cache:
  yarn: true

env:
  # Do two runs, one for testing and one for linting.
  matrix:
    - TEST_TYPE=lint
    - TEST_TYPE=test

script:
  # Run testing or linting depending on the environment.
  - yarn run $TEST_TYPE
